### ISSUE TITLE
 gérer les formations

### ISSUE THREAD

**Issue by DamienNEEL** [CNED-SLAM/mediatekformation#11]

**Comment by CNED-SLAM** [comment]
Bonjour,
Pourquoi avoir ajouté ce commentaire, qui contient juste une des tâches demandée, sur mon dépôt ?

**Comment by DamienNEEL** [comment]
Je n'arrive pas à supprimer cela, il y a t'il une procédure particulière?

Le mer. 4 janv. 2023 à 15:33, Damien Neel ***@***.***> a
écrit :
